### ISSUE TITLE
OTSea Audit Request

### ISSUE THREAD

**Issue by 0xlucius** [CallistoSecurity/Smart-contract-auditing#13]
# Audit request

[OTSea](https://otsea.xyz) is a simple OTC platform where users can exchange ERC20 tokens easily. The orders can be fulfilled by one or many buyers, and the order owner can settle the order anytime. 

# Source code

Link: https://vscode.blockscan.com/ethereum/0x28a2f7849f0a2bccf1f5d246cef5a6867a5bfa23

# Payment plan

While not standard, it is a very small contract (<400 LOC). Looking for a quote closer to standard.

- [x] Standard (standard projects such as ICOs, ERC20, ERC223, ERC721, ERC721A tokens and NFTs fall in this category - 2 auditors. $600 + $1.2 per line of code / minimum $1200)
- [ ] Advanced (non-standard projects requiring more careful review - 3 auditors. $1200 + $1.5 per line / minimum $2400)
- [ ] Corporate (projects that require post-launch support - 3 auditors - Callisto Team will handle the bugbounty and provide a 1 month long period of technical support regarding the necessary security enhancement procedures and track/highlight any issues and potential threats - this plan allows to further apply for Callisto DAPP Insurance program)

# Disclosure policy

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

otseaerc20@gmail.com

or Telegram
lucius0x
optimus0x

# Platform

Deployed in ETH Mainnet as Beta at 0x28a2f7849f0a2bccf1f5d246cef5a6867a5bfa23

**Comment by yuriy77k** [comment]
@0xlucius 
The audit fee is 1200 USDT.
You may send USDT (ERC20 or BEP20) to: 0x6317c6944bd1cD3932d062cce39d7Fd602119529 (valid for Ethereum and Binance Smart Chain)

The estimated auditing time - is 7 days after payment.
