### ISSUE TITLE
Audit: token-operating smart contracts

### ISSUE THREAD

**Issue by RobertBobor** [CallistoSecurity/Smart-contract-auditing#26]
# Audit request
We would like to have 4 smart contracts to be audited:
- vesting/VestingFactory.sol
- staking/Staking.sol
- token/Launchpad.sol
- generic/TimeMultisig.sol
Descriptions for each of them can be found in README files in corresponding folders.

# Source code
https://github.com/VIS-DEI/smart-contracts-public/tree/main/contracts

# Payment plan
- [ ] Standard (standard projects such as ICOs, ERC20, ERC223, ERC721, ERC721A tokens and NFTs fall in this category - 2 auditors. $600 + $1.2 per line of code / minimum $1200)
- [x] Advanced (non-standard projects requiring more careful review - 3 auditors. $1200 + $1.5 per line / minimum $2400)
- [ ] Corporate (projects that require post-launch support - 3 auditors - Callisto Team will handle the bugbounty and provide a 1 month long period of technical support regarding the necessary security enhancement procedures and track/highlight any issues and potential threats - this plan allows to further apply for Callisto DAPP Insurance program)

# Disclosure policy
Please notify me privately.

# Contact information (optional)
robert.bobor@dei.cz

# Platform
ETH

**Comment by yuriy77k** [comment]
@RobertBobor The audit fee is 2400 USDT.
You may send USDT (ERC20 or BEP20) to: 0x6317c6944bd1cD3932d062cce39d7Fd602119529 (valid for Ethereum and Binance Smart Chain)

**Comment by yuriy77k** [comment]
Payment received

**Comment by yuriy77k** [comment]
@RobertBobor The high severity issues where found. The report was sent to you by email.
