### ISSUE TITLE
Match-Contract

### ISSUE THREAD

**Issue by onn-mah** [CallistoSecurity/Smart-contract-auditing#6]
# Audit request

Contract locks some tokens and will be released upon date maturity and chainlink response.

# Source code

... Give a link to the source code of contracts ...
https://github.com/technine-IT/match-contract

# Payment plan

... Write [x] at the checkbox of the payment plan that suits your needs ...

- [ ] Standard (standard projects such as ICOs, ERC20, ERC223, ERC721, ERC721A tokens and NFTs fall in this category - 2 auditors. $500 + $1 per line of code / minimum $1000)
- [x] Advanced (non-standard projects requiring more careful review - 3 auditors. $1000 + $1.25 per line / minimum $2000)
- [ ] Corporate (projects that require post-launch support - 3 auditors - Callisto Team will handle the bugbounty and provide a 1 month long period of technical support regarding the necessary security enhancement procedures and track/highlight any issues and potential threats - this plan allows to further apply for Callisto DAPP Insurance program)

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...
Private pelase

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...\
onn.mah@technine.io

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...
None yet

# Platform

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...
Ethereum

**Comment by yuriy77k** [comment]
@onn-mah 
The audit fee is 200p USDT.
You may send USDT (ERC20 or BEP20) to: 0x6317c6944bd1cD3932d062cce39d7Fd602119529 (valid for Ethereum and Binance Smart Chain)

The estimated auditing time - is 4 days after payment.

**Comment by yuriy77k** [comment]
payment: https://www.bscscan.com/tx/0x0e0e430e127a73dddcb875bcbb95ea14c4483d071ac2fe1c70a189f53ca3dd48

**Comment by yuriy77k** [comment]
# Match-Contract v2 Security Audit Report

# 1. Summary

[Match-Contract](https://github.com/JPEX-IT/match-contract) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/CallistoSecurity/Smart-contract-auditing)

# 2. In scope

Commit `fea60fd9f38f485c21c3cf1076a4a213b1ff0043`

- [Match.sol](https://github.com/JPEX-IT/match-contract/blob/fea60fd9f38f485c21c3cf1076a4a213b1ff0043/contract/Match.sol)

## 2.1. Excluded from audit

Imported contracts from Chainlink and Openzeppelin were excluded from audits.

# 3. Findings

In total, **2 issues** were reported, including:

- 0 high severity issueS.

- 0 medium severity issues.

- 0 low severity issueS.

In total, **3 notes** were reported, including:

- 3 notes.

- 0 owner privileges.

No critical security issues were found.


## 3.1. Centralized source of the result

### Severity: note

### Description

The winner is chosen according to the result obtained from "https://api.derektoyzboxing.com/result" received from Operator contract "0x1db329cDE457D68B872766F4e12F9532BCA9149b". How the result is generated and how the operator translates it to this contract is not possible to confirm in this audit.

So users should trust them if they agree to use this contract. 


## 3.2. Follow good coding practice

### Severity: note

### Description

1. Missing docstrings

The contracts in the code base lack documentation. This hinders reviewers’ understanding of the code’s intention, which is fundamental to correctly assess not only security but also correctness. Additionally, docstrings improve readability and ease maintenance. They should explicitly explain the purpose or intention of the functions, the scenarios under which they can fail, the roles allowed to call them, the values returned, and the events emitted.

Consider thoroughly documenting all functions (and their parameters) that are part of the contracts’ public API. Functions implementing sensitive functionality, even if not public, should be documented as well. When writing docstrings, consider following the Ethereum Natural Specification Format (NatSpec).

2. Missing test suite

The contract is missing a test suite to validate and verify the behavior of the contract functionalities. Add tests are recommended to ensure that the contract functions and behaves as expected.


## 3.3. Inherited `transferOwnership` function does not change real contract owner

### Severity: note

### Description

The inherited contract `ConfirmedOwner` has `transferOwnership()` function, but this function did not change `_owner` variable that is used in the `Match` contract. So owner should be aware that ownership is not transferable.


# 4. Security practices

- [ ] **Open-source contact**.
- [ ] **The contract should pass a bug bounty after the completion of the security audit.**
- [ ] **Public testing.**
- [ ] **Automated anomaly detection systems.** - NOT IMPLEMENTED. A simple anomaly detection algorithm is recommended to be implemented to detect behavior that is atypical compared to normal for this contract. For instance, the contract must halt deposits in case a large amount is being withdrawn in a short period of time until the owner or the community of the contract approves further operations.
- [ ] **Multisig owner account.**
- [ ] **Standard ERC20-related issues.** - NOT IMPLEMENTED. It is known that every contract can potentially receive an unintended ERC20-token deposit without the ability to reject it even if the contract is not intended to receive or hold tokens. As a result, it is recommended to implement a function that will allow extracting any arbitrary number of tokens from the contract.
- [ ] **Crosschain address collisions.** ETH, ETC, CLO, etc. It is possible that a transaction can be sent to the address of your contract at another chain (as a result of a user mistake or some software fault). It is recommended that you deploy a "mock contract" that would allow you to withdraw any tokens from that address or prevent any funds deposits. Note that you can reject transactions of native token deposited, but you can not reject the deposits of ERC20 tokens. You can use this source code as a mock contract: [extractor contract source code](https://github.com/EthereumCommonwealth/GNT-emergency-extractor-contract/blob/master/extractor.sol). The address of a new contract deployed using `CREATE (0xf0)` opcode is assigned following this scheme `keccak256(rlp([sender, nonce]))`. Therefore you need to use the same address that was originally used at the main chain to deploy the mock contract at a transaction with the `nonce` that matches that on the original chain. _Example: If you have deployed your main contract with address 0x010101 at your 2021th transaction then you need to increase your nonce of 0x010101 address to 2020 at the chain where your mock contract will be deployed. Then you can deploy your mock contract with your 2021th transaction, and it will receive the same address as your mainnet contract._

# 5. Conclusion

The audited smart contract can be deployed. No security issues were found during the audit.

Users should pay attention to the centralized source of choosing the winner. Users should understand that Operator and API provider can manipulate results. 

It is recommended to adhere to the security practices described in pt. 4 of this report to ensure the contract's operability and prevent any issues that are not directly related to the code of this smart contract.

# 6. Revealing previous audit reports

- https://gist.github.com/yuriy77k/842a06f4e849c6d5f94590fcfb108741
